/*
 *
 * Copyright (c) 2021 The Ontario Institute for Cancer Research. All rights reserved
 *
 *  This program and the accompanying materials are made available under the terms of
 *  the GNU Affero General Public License v3.0. You should have received a copy of the
 *  GNU Affero General Public License along with this program.
 *   If not, see <http://www.gnu.org/licenses/>.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 *  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 *  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 *  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 *  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/* eslint-disable */

import { useRef, useEffect } from 'react';

import useScriptTag from '../../../global/hooks/useScriptTag';
import PageLayout from '../../PageLayout';
import './lib/jquery-ui.css';
import styles from './VisualizationComponent.module.css';

const VisualizationComponent = () => {
  const scriptRef = useRef(null);
  const dialogRef = useRef(null);

  const jQueryLoaded = useScriptTag({
    parentRef: scriptRef,
    src: '//code.jquery.com/jquery-3.6.0.min.js',
  });

  const jQueryUILoaded = useScriptTag({
    dependency: jQueryLoaded,
    parentRef: scriptRef,
    src: '//code.jquery.com/ui/1.13.0/jquery-ui.min.js',
  });

  useEffect(() => {
    // check that jQuery & jQuery-UI are loaded and available
    const hasjQueryUI = !!(jQueryUILoaded && window.jQuery);

    // store ref.current, in case it changes.
    const scriptRef = dialogRef.current;

    if (hasjQueryUI) {
      // instantiate jQuery & jQuery-UI functions
      scriptRef && $(scriptRef).tooltip({ show: null });
    }

    return () => {
      // cleanup
      if (hasjQueryUI) {
        scriptRef && $(scriptRef).tooltip('destroy');
      }
    };
  }, [jQueryUILoaded]);

  return (
    <PageLayout subtitle="JQuery Test">
      <div className={styles.covizu} ref={scriptRef}>
        {jQueryUILoaded ? (
          <>
            <div className="tooltip" id="tooltipContainer"></div>

            <div id="splash" title="Welcome">
              <p>
                <b>CoVizu</b> is an{' '}
                <a href="https://github.com/PoonLab/CoVizu" target="_blank">
                  open source project
                </a>
                endeavouring to visualize the global diversity of SARS-CoV-2 genomes.
              </p>
              <p>
                This web page provides two interactive visualizations of these data. On the left, it
                displays a{' '}
                <a href="https://en.wikipedia.org/wiki/Phylogenetic_tree" target="_blank">
                  phylogenetic tree
                </a>{' '}
                summarizing the evolutionary relationships among different
                <a href="https://cov-lineages.org" target="_blank">
                  SARS-CoV-2 lineages
                </a>{' '}
                (groupings of viruses with similar genomes, useful for linking outbreaks in
                different places;{' '}
                <a href="https://www.nature.com/articles/s41564-020-0770-5" target="_blank">
                  Rambaut
                  <i>et al.</i> 2020
                </a>
                ). You can navigate between different lineages by clicking on their respective
                boxes.
              </p>
              <p>
                Selecting a lineage displays a "beadplot" visualization in the centre of the page.
                Each horizontal line represents one or more samples of SARS-CoV-2 that share the
                same genome sequence. Beads along the line represent the dates that this variant was
                sampled.
              </p>
              <p>
                For more help, click on the
                <a
                  style={{ textDecoration: 'none' }}
                  href="https://en.wikipedia.org/wiki/Shoshinsha_mark"
                  target="_blank"
                >
                  &#128304;
                </a>
                icons.
              </p>
            </div>

            <div id="help-timetree" title="Help: Time-scaled tree interface">
              <p>
                A phylogenetic tree is a model of how different populations are related by common
                ancestors. The tree displayed here (generated by{' '}
                <a href="https://github.com/neherlab/treetime">TreeTime</a> v0.8.0) summarizes the
                common ancestry of different
                <a href="https://cov-lineages.org" target="_blank">
                  SARS-CoV-2 lineages
                </a>
                , which are pre-defined groupings of viruses based on genome similarity.
              </p>
              <p>
                A time scale is drawn above the tree marked with
                <a href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">
                  dates
                </a>
                . The earliest ancestor (root) is drawn on the left, and the most recent observed
                descendants are on the right. We estimate the dates of common ancestors by comparing
                the sampled genomes and assuming a{' '}
                <a
                  href="http://virological.org/t/phylodynamic-analysis-176-genomes-6-mar-2020/356"
                  target="_blank"
                >
                  constant rate
                </a>{' '}
                of evolution.
              </p>
              <p>
                For each lineage, we draw a rectangle to summarize the range of sample collection
                dates, and colour it according to the geographic region it was sampled most often.
                To explore the samples within a lineage, click on the label (<i>e.g.,</i> "B.4") or
                the rectangle to retrieve the associated beadplot.
              </p>
            </div>

            <div id="help-beadplot" title="Help: Beadplot interface">
              <p>
                We use beadplots to visualize the different variants of SARS-CoV-2 within a
                <a href="https://cov-lineages.org" target="_blank">
                  lineage
                </a>
                , where and when they have been sampled, and how they are related to each other.
                Every object in the beadplot has additional info in a tooltip (which you view by
                hovering over that object with your mouse pointer).
              </p>
              <p>
                Each horizontal line segment represents a variant &ndash; viruses with
                <span
                  className="hint"
                  title="It's a bit more complicated.  Many genomes are identical in sequence, but many more have missing information - parts of the genome that have not been sequenced.  Since we can't be 100% certain two genomes with missing parts are identical, we randomly re-sample genomes 100 times (non-parametric bootstrap) and evaluate how often they are separated in our analysis."
                >
                  identical
                </span>
                genomes. We draw beads along a line to indicate when that variant was sampled. If
                there are no beads on the line and it is grey, then it is an unsampled variant: two
                or more sampled variants descend from an ancestral variant that has not been
                directly observed.
              </p>
              <p>
                The area of the bead is scaled in proportion to the number of times the variant was
                sampled that day. This is important for rapid or intensively-sampled epidemics,{' '}
                <i>e.g.,</i>
                lineage D.2 in Australia. Beads are{' '}
                <span
                  className="hint"
                  title="Refer to the barplot in the Countries tab in the right panel for a colour legend."
                >
                  coloured
                </span>
                with respect to the most common geographic region of the samples.
              </p>
              <p>
                We draw vertical line segments to connects variants to their
                <span
                  className="hint"
                  title="The direction of ancestor-descendant relationships is, in effect, determined by degree size.  This is a crude estimate, so be cautious about interpreting the directionality of these relationships."
                >
                  common ancestors
                </span>
                . These relationships are estimated by the{' '}
                <a href="https://en.wikipedia.org/wiki/Neighbor_joining">neighbor-joining method</a>{' '}
                using
                <a href="https://birc.au.dk/software/rapidnj/">RapidNJ</a>. Tooltips for each edge
                report the number of genetic differences (mutations) between ancestor and descendant
                as the "genomic distance". Since it's difficult to reconstruct exactly when these
                mutations occurred, we simply map each line to when the first sample was collected.
              </p>
            </div>

            <div id="help-search" title="Help: Search interface">
              <p>
                Since there is an overwhelming number of sampled infections that we are trying to
                visualize here, we have built a basic search interface that you can interact with
                using the inputs at the top of this web page.
              </p>
              <p>
                You can use the text box to find a specific sample by GISAID accession number. If
                you start to enter an accession number, the text box will display a number of
                possibilities (autocompletion). You can also search samples by substring
                (case-sensitive). For example, searching for "Madaga" (hit enter to submit) will
                jump to the first lineage that contains a sample from Madagascar.
              </p>
              <p>
                Use the "Previous" and "Next" buttons to iterate through your search results, and
                the "Clear" button to reset the search interface.
              </p>
            </div>
          </>
        ) : (
          <p>Loading</p>
        )}
      </div>
    </PageLayout>
  );
};

export default VisualizationComponent;
